from backend.wallet.transaction import Transaction


class TransactionPool:
    def __init__(self):
        self.transaction_map: dict[str, Transaction] = {}

    def set_transaction(self, transaction: Transaction):
        """
        Set a transaction in the transaction pool
        :param transaction:
        :return:
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Find a transaction generated by the address in the transaction pool
        :param address:
        :return:
        """
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == address:
                return transaction

    def transaction_data(self):
        """
        Return the transactions of the transaction poool represented in their JSON format
        :return:
        """
        return list(map(
                lambda transaction: transaction.to_json(),
                self.transaction_map.values()
        ))

    def clear_blockchain_transactions(self, blockchain):
        """
        Delete blockchain transactions recorded in the transaction pool
        :param blockchain:
        :return:
        """
        for block in blockchain.chain:
            for transaction in block.data:
                try:
                    del self.transaction_map[transaction['id']]
                except KeyError:
                    pass



