from backend.wallet.transaction import Transaction


class TransactionPool:
    def __init__(self):
        self.transaction_map: dict[str, Transaction] = {}

    def set_transaction(self, transaction: Transaction):
        """
        Set a transaction in the transaction pool
        :param transaction:
        :return:
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Find a transaction generated by the address in the transaction pool
        :param address:
        :return:
        """
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == address:
                return transaction


